server:
  port: 8802

spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  # actuator 健康检查需要配置，不配置会尝试去连接 localhost
  rabbitmq:
    password: root
    username: root
    host: 180.76.231.102
    port: 5672
  cloud:
    stream:
      binders: # 在此处配置需要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于binding 整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq相关环境
            spring:
              rabbitmq:
                password: root
                username: root
                host: 180.76.231.102
                port: 5672
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道名称 这里是接收消息
          destination: studyExchange # 表示要使用Exchange 名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置为 “text/plain”
          binder: defaultRabbit # 爆红不用管
          group: A_Group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802.com
    prefer-ip-address: true
