server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率在0 到 1 之间， 1则表示全部采样
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 942699
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7003/eureka
  instance:
    instance-id: payment8001 # 主机名称
    prefer-ip-address: true # 显示ip地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.tfyhyc.springcloud.entities # 所有Entity别名坐在的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
