server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh               #路由的ID，没有固定规则，但要求唯一，建议配合服务名称
#          uri: http://localhost:8001      #匹配后提供的服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #动态分配
          predicates:
            - Path=/payment/get/**        # 断言，路径匹配相配置的进行路由
            - After=2022-10-16T18:01:47.561+08:00[Asia/Shanghai]
            - Cookie=zhangx,zx
        - id: payment_routh2
#          uri:  http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7003/eureka